### ISSUE TITLE
Transfer from cluster training to local - unsupervised DeepOF

### ISSUE THREAD

**Issue by veronikakvr** [lucasmiranda42/deepof#1]
When training the unsupervised model  on a cluster due to high computational demand, I have troubles to then run the supervised analysis on my local computer - in order to get to the interpretation of the identified clusters. - e.g. confusion matrix, SHAP values.

I get following error: _FileNotFoundError: [Errno 2] No such file or directory: '/u/user/conda-envs/deepof/lib/python3.9/site-packages/deepof/trained_models\\deepof_supervised\\deepof_supervised_huddle_estimator.pkl'_

Disclaimer: "/u/user" is the directory utilized in the cluster.

The work flow (general outline follows the online tutorial):
- automatic circular arena detection 
- project created on local computer 
- loaded in cluster and progressed with the coord generation and training the model
- transfered back to local computer and loading everything together with "pretrained=True" in trained model
- first hickup occurs after Entropy plots are generated

My question is - what is the flexibility of transporting deepof_project between clusters and local computers/local to local computer?

Thanks a lot in advance!

**Comment by lucasmiranda42** [comment]
Dear @veronikakvr,

Thank you for your interest in DeepOF! This was a known issue up until a few releases ago, where there was a bug with how the paths to the trained models were stored in the `Coordinates` class. In the current implementation, the path should be reloaded every time you run the `supervised_annotation` method. Could you confirm that you're using the last version of the package (v0.6)?

If not, or if you understandably don't want to update when everything worked so far, you can patch the issue by overriding the `.trained_path` method on your local environment:

```python
my_deepof_project._project_path = os.path.join("/".join(deepof.__file__.split("/")[:-1]), "trained_models/deepof_supervised/deepof_supervised_huddle_estimator.pkl")
```

(replace my_deepof_project by your current project name)

Best, and let us know if it works!
Lucas

**Comment by veronikakvr** [comment]
Hello Lucas,

The update to the latest version of DeepOF, helped. The problem is solved :)

Thanks!

**Comment by lucasmiranda42** [comment]
Amazing, glad to hear!
